{% set name = "click-log" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 3970f8570ac54491237bcdb3d8ab5e3eef6c057df29f8c3d1151a51a9c23b975

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - click

test:
  requires:
    - pytest
    - python {{ python_min }}
  source_files:
    - tests
  imports:
    - click_log
  commands:
    - pytest tests/

about:
  home: https://github.com/click-contrib/click-log
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Logging integration for Click
  description: |
    Simple and beautiful logging for click applications
  doc_url: https://click-log.readthedocs.io
  dev_url: https://github.com/click-contrib/click-log

extra:
  recipe-maintainers:
    - CurtLH
    - anjos
